---

akamai :
  open :
    client_secret : ""
    host : ""
    access_token : ""
    client_token : ""
  netstorage : 
    host : ""
    upload_account : ""
    cp_code : ""
    key : ""
    use_ssl : false
