---

splunk : # Optional. Splunk delivery config. Delete if using Wazuh/Syslog delivery
  host : '127.0.0.1'            # Splunk deployment's host name / IP
  hec_port : 8088               # HEC port
  hec_use_ssl : false           # HEC use SSL
  lds_hec :
    token : ''                    # HEC token for LogDeliveryService logs
    source_type: 'lds_log_dns'    # Optional. Override HEC token default source type 
    index: 'sandbox'              # Optional. Override HEC token's default index. Must be in HEC token's allow list
    batch_size: 20                # Optional. Default 10. Number of events to send Splunk in single request
  edgedns_hec : # Optional
    token : ''                    # HEC token for Edge DNS zone records
    source_type: 'edgedns_log'    # Optional. Override HEC token default source type 
    index: 'sandbox'              # Optional. Override HEC token's default index. Must be in HEC token's allow list
    batch_size: 20                # Optional. Default 10. Number of events to send Splunk in single request

syslog : # SysLog delivery config. Delete if using Splunk delivery
  host : '127.0.0.1'                    # SysLog server host name / IP
  port: 513                             # SysLog server port
  protocol: 'TCP'                       # SysLog protocol: UDP, TCP, or TCP_TLS
  use_tcp : true                        # Deprecated. Use protocol. Whether to use TCP or UDP. 
  lds_app_name : 'lds_dns_log'          # SysLog app name field for LDS messages
  edgedns_app_name : 'lds_dns_record'   # SysLog app name field for Edge DNS config messages
  append_null: true                     # Optional. Append 0x00 between SysLog message. Some servers require this
  from_host: 'example.com'              # Optional. SysLog hostname field. If not set, use system's host name
  tls :                                 # Optional. Required for TCP_TLS protocol
    ca_file: 'ca.pem'                   # Certificate authority used to validate server's certificate
    verify: true                        # Optional. Default true. Whether to verify server's hostname against certificate

edgedns : # Optional. Record Set Delivery feature's config
  send_records : true       # Fetch + send zone_name's resource records. Open must be configured
  zone_name : 'example.com' # Zone to send records for
  poll_period_sec : 3600    # Optional. Default 7200. Poll period in seconds

open : # Optional. Akamai API credentials used for Record Set Delivery feature
  client_secret : ''      # Client secret
  host : ''               # Host
  access_token : ''       # Access token
  client_token : ''       # Client token
  account_switch_key : '' # Optional. Account switch key

lds : # LogDeliveryService configuration
  ns : # NetStorage configuration
    host : ''               # HTTP domain name
    upload_account : ''     # Upload account ID
    cp_code : ''            # Upload directory's CP code
    key : ''                # HTTP CMS API key
    use_ssl : false         # Use SSL for NetStorage API
    log_dir : 'logs'        # Log directory path
  log_download_dir : 'tmp/'                   # Local log download directory
  timestamp_parse: '{} - {} {timestamp},{}'   # Timestamp parse format. Parses timestamp substring from log line
  timestamp_strptime: '%d/%m/%Y %H:%M:%S'     # Timestamp strptime format. Parses timestamp substring into datetime
  log_poll_period_sec : 30                    # Optional. Default 60. NetStorage log poll period in seconds