---

splunk :
  hec :
    host : "127.0.0.1"
    port : 8088
    token : ""
    use_ssl : false

akamai :
  open :
    client_secret : ""
    host : ""
    access_token : ""
    client_token : ""
  netstorage : 
    host : ""
    upload_account : ""
    cp_code : ""
    key : ""
    use_ssl : false
    log_dir : 'logs'

connector :
  log_download_dir : 'tmp/'