---

splunk :
  host : "127.0.0.1"
  source_type: "lds_log_dns"
  index: "sandbox"
  hec :
    port : 8088
    token : ""
    use_ssl : false

akamai :
  netstorage : 
    host : ""
    upload_account : ""
    cp_code : ""
    key : ""
    use_ssl : false
    log_dir : 'logs'

connector :
  log_download_dir : 'tmp/'  
  timestamp_parse: '{} - {} {timestamp},{}'
  timestamp_strptime: '%d/%m/%Y %H:%M:%S'
  log_poll_period_sec : 30